version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laraflix
    image: laraflix
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laraflix
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laraflix
networks:
  laraflix:
    driver: bridge
